### PR TITLE
[WIP] 9.0 mig + tecnativa imp + catalog manager

### PR DESCRIPTION
**Pull request by simahawk**
Continuing the work started here https://github.com/OCA/connector-prestashop/pull/24
- [x] port the last changes from the 8.0 version
- [x] import of refunds seems deeply broken
- [x] port the catalog manager module
- [x] use requests in prestapyt so we can use vrc.py for the tests (prestapyt/prestapyt#37 should be merged and a new release of prestapyt published when we are confident with the changes)
- [ ] review the silent try: except: pass which seem questionable **[WIP]**
- [ ] every synchronization should be tested, reviewed and get a test suite (with vcr.py)
- [ ] investigate reason for the 'virtual' model _import_stock_available instead of using prestashop.product.template
- [ ] handle sale order states better according to odoo 9.0 changes: the 'done' state is meaningless for PrestaShop, but we'd want to know when an order is delivered and / or invoiced
- [ ] make a pass through the TODOs and FIXMEs
- [ ] update existing attribute values
  As described in https://github.com/guewen/connector-prestashop/pull/5#issuecomment-254492750 if you already have an attribute value with the same name in odoo the import is broken. Pedro suggests to follow [this approach](https://github.com/OCA/connector-magento/pull/219/files).
- [ ] Add debug option for the API
- [ ] Add some matching options for taxes / product / partner
- [ ] kanban view for the backend (see woo-commerce)

**Notes**
Depends on `product_multi_image` porting https://github.com/OCA/product-attribute/pull/161
Sodexis fork has been added to `oca_dependencies.txt`. Drop it when merged.

### CODE REVIEW

**Comment by simahawk** [comment]
@pedrobaeza I'm continuing the work here temporarily.

Hopefully I've merged all of your updates but the catalog manager (TODO).
RIght now I'm going trough every import to test it and add unit tests when possible.

Current issue is: when importing combinations I get

```
IntegrityError: duplicate key value violates unique constraint "product_attribute_value_value_company_uniq"
DETAIL:  Key (name, attribute_id)=(White, 2) already exists.
```

Full traceback here http://pastebin.com/xp16bFuK

I wonder if this constraint is something that we really want or if I'm missing some fix/update from somewhere.

**Comment by pedrobaeza** [comment]
I think that restriction come from Odoo itself, but it's logic. You can have 2 times the value "White" in the same attribute. It comes for a bad PrestaShop definition or a partial import that duplicates this value. Please check which one is and we can see.

**Comment by simahawk** [comment]
@pedrobaeza yes, is a std odoo constraint, here:

```
parts/odoo/addons/product/product.py:        ('value_company_uniq', 'unique (name,attribute_id)', 'This attribute value already exists !')
```

and I found why is it failing: if you load demo data (as I did) you get some default attr values:

```
# select id,name from product_attribute_value;
 id |  name   
----+---------
[...]
  3 | White
  4 | Black
[...]
```

and in demo PS you have the same values. Renaming the values on PS side works :)
I just wonder if this is a desired behavior...
If you don't sync values from odoo to PS (using catalog mngr for instance) and you create values directly from odoo (like my case) you break the sync.

**Comment by pedrobaeza** [comment]
For avoiding that, we should include matching rules for avoid the creation of new records, the same as it has been done for example in products in Magento matching internal reference. See https://github.com/OCA/connector-magento/pull/219/files. I'm not sure if this case can be a bit more complicated as everything is created together, but not too much for you for sure :wink:

**Comment by simahawk** [comment]
@pedrobaeza ok, thanks for the pointer. I'll add it to TODO list.

BTW: by chance... did you started adding unit tests? :)

**Comment by pedrobaeza** [comment]
I'm afraid not. `mock` is still a forbidden area for me because lack of time.

**Comment by simahawk** [comment]
@pedrobaeza about translations:

[here in product mapper](https://github.com/simahawk/connector-prestashop/blob/9.0-mig%2Btecnativa-imp/connector_prestashop_catalog_manager/product.py#L379) we translate attributes in a specific mapper (as in all the other mappers) but [here in base mapper](https://github.com/simahawk/connector-prestashop/blob/9.0-mig%2Btecnativa-imp/connector_prestashop/unit/mapper.py#L24) we force the translation using `self.translated_fields` which could not exists or be a `@mapping` method as in the link above.

The main issue is that `convert` and `_convert` are no longer there so I need to know if I can remove that override since we already translating values in specific mappers. In this case I will keep only helper methods like `convert_languages`. Any pointer?

**Comment by simahawk** [comment]
@pedrobaeza I think I got it working :)
Can you please review this https://github.com/guewen/connector-prestashop/pull/5/commits/6c7a11e2ffc76eb2ece3d2cc24e208edb5bfa3c0 ?
Basically I moved the translation logic to the base mapper and you just need define `_translatable_fields` in your custom mapper.

**Comment by pedrobaeza** [comment]
For that, @sergio-teruel should be the one that answers, that he was the guy that implements translations.

**Comment by simahawk** [comment]
@sergio-teruel can you review this? https://github.com/guewen/connector-prestashop/pull/5/commits/6c7a11e2ffc76eb2ece3d2cc24e208edb5bfa3c0

**Comment by pedrobaeza** [comment]
@sergio-teruel is today out, but I think tomorrow he will be able to check it.

**Comment by simahawk** [comment]
@pedrobaeza https://travis-ci.org/simahawk/connector-prestashop/jobs/170510723#L902

the build fails because of missing code from PRs like https://github.com/OCA/product-attribute/pull/161

Should I add `sodexis:9.0-product_multi_image` to oca_dependencies.txt or is there a way to reference a PR?

**Comment by damdam-s** [comment]
@simahawk I think you can add a reference to `sodexis:9.0-product_multi_image` branch in the oca_dependencies.txt`.
An example: https://github.com/OCA/maintainer-quality-tools/blob/master/tests/test_repo/oca_dependencies.txt

Just make yourself a note to remove it when the sodexis branch will be merged

**Comment by pedrobaeza** [comment]
The other option is to push further (or superseed) the merge of the module.

**Pull request merged**
